GET http://localhost:3000/api/v1/articles

###

GET http://localhost:3000/api/v1/articles?skip=10&take=25


###

GET http://localhost:3000/api/v1/articles/10

###

POST http://localhost:3000/api/v1/articles
Content-Type: application/json

{
    "title": "my First Blog",
    "content": "My first Blog ever! I'm so excited Sheesh!",
    "image" : "cats.png",
    "isPublished": true,
    "userId": 6,
    "categoryArray": [2,3]
}


###

PUT http://localhost:3000/api/v1/articles/3
Content-Type: application/json

{
    "categoryArray" : [4]
}


###

DELETE http://localhost:3000/api/v1/articles/35