// TODO: Implement HTTP Requests


GET http://localhost:3000/api/v1/articles

###

GET http://localhost:3000/api/v1/articles/1

###

POST http://localhost:3000/api/v1/articles
Content-Type: application/json

{
    "title": "my First Blog",
    "content": "My first Blog ever! I'm so excited Sheesh!",
    "image" : "cats.png",
    "isPublished": true,
    "userId": 5,
    "categoryId": 1
}


###

PUT http://localhost:3000/api/v1/articles/1
Content-Type: application/json

{
    "title" : "Update to my first blog"
}


###

DELETE http://localhost:3000/api/v1/articles/1